### ISSUE TITLE
imagery.json should come from settings

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-settings#1]
@okdistribute is there a reason for reading `imagery.json` from `this.userDataPath` https://github.com/digidem/mapeo-settings/blob/master/index.js#L38? I think where we use this file (e.g. [presets-wao](https://github.com/digidem/presets-wao)) it is included in the `.mapeosettings` file. Just wondering if this is like this for some kind of legacy support? Otherwise we should change it.

**Comment by okdistribute** [comment]
Oh interesting. Probably legacy... maybe we could consider merging them if we're worried about backwards compat? Otherwise since everything else is getting pulled from `this.defaultPath`, it seems like it would make sense that this should too.

**Comment by okdistribute** [comment]
I don't think we need to keep userDataPath around for imagery anymore
